<?php
require_once __DIR__ . '/include/site_settings.php';
require_once __DIR__ . '/config/db.php';
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>RESULT — RKDF University Bhopal</title>
  <link rel="stylesheet" href="css/rkdf-home.css">
  <style>
    .subpage-hero {
      position: relative;
      padding: 160px 0 90px;
      background: linear-gradient(135deg, rgba(12,20,36,0.94) 0%, rgba(21,34,56,0.90) 60%, rgba(12,20,36,0.96) 100%), 
                  url('images/lovable/rkdf-why-bg.jpg') center/cover no-repeat;
      color: var(--p-paper);
      box-shadow: inset 0 -30px 60px rgba(0,0,0,0.4);
    }
    .sp-main-box {
      padding: 80px 0;
      background: var(--p-paper);
      color: var(--p-navy-deep);
      font-size: 16px;
      line-height: 1.8;
    }
    .sp-main-box table {
      width: 100%;
      border-collapse: collapse;
      margin: 28px 0;
      background: #ffffff;
      border-radius: 12px;
      overflow: hidden;
      box-shadow: 0 4px 16px rgba(12,20,36,0.04);
      border: 1px solid var(--p-hairline);
    }
    .sp-main-box th {
      background: var(--p-navy-deep);
      color: #ffffff;
      padding: 16px 20px;
      font-family: var(--p-font-mono);
      font-size: 13.5px;
      text-transform: uppercase;
      letter-spacing: 0.05em;
    }
    .sp-main-box td {
      padding: 16px 20px;
      border-bottom: 1px solid var(--p-hairline);
      font-size: 15px;
    }
    .sp-main-box tr:hover td {
      background: rgba(220,38,38,0.03);
    }
    .sp-main-box a {
      color: var(--p-gold);
      font-weight: 700;
      text-decoration: none;
      transition: color 0.2s;
    }
    .sp-main-box a:hover {
      text-decoration: underline;
      color: #b91c1c;
    }
    .sp-main-box img {
      max-width: 100%;
      height: auto;
      border-radius: 12px;
      object-fit: contain;
    }
    .glossymenu a.menuitem {
      display: inline-block;
      padding: 10px 18px;
      margin: 4px;
      background: #ffffff;
      border: 1px solid var(--p-hairline);
      border-radius: 8px;
      color: var(--p-navy-deep);
      font-weight: 700;
      text-decoration: none;
      transition: all 0.25s;
    }
    .glossymenu a.menuitem:hover {
      background: var(--p-gold);
      color: #ffffff;
      border-color: var(--p-gold);
    }
  </style>
</head>
<body>
  <!-- APPROVED NAVBAR -->
  <?php include __DIR__ . '/include/new_navbar.php'; ?>

  <!-- HERO SECTION -->
  <section class="subpage-hero">
    <div class="rk-container">
      <span class="rk-eyebrow tone-gold">RKDF University Bhopal</span>
      <h1 class="rk-h1" style="font-size:clamp(2.5rem, 5.5vw, 5.2rem);margin-top:12px;">RESULT</h1>
    </div>
  </section>

  <!-- MAIN CONTENT SECTION (100% Exact Original Inner Content & Links Preserved) -->
  <section class="sp-main-box">
    <div class="rk-container">
<section id="content" class="wrapper ">
        <!--- spotlight -->
        <strong>RKDF UNIVERSITY RESULT DECLARED (Pending...)</strong>
        <p>&nbsp;</p>

        <section id="contentLeft">
            <!-- <img src="images/img/result.png" width="336" height="101" /> -->

            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <br />

            <div align="justify"></div>
            <a href="https://www.rkdf.ac.in/exam.php"
                style="font-size: medium;font-style: normal;font-weight: bolder;color: navy;">View Examination
                Notices</a> <br />

            <p style="font-size: medium;font-style: normal;font-weight: bolder;color: navy;">&nbsp;
                <h2>Results FEB - 2025</h2>
            </p>
            <p></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />BHMS - REVALUATION - 2/3/4 - REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />BHMS - REVALUATION - 2/3 - REAPPEAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>


            <p style="font-size: medium;font-style: normal;font-weight: bolder;color: navy;">&nbsp;
            <h2>Results June - 2025</h2>
            </p>
            <p></p>

            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />B.PHARM - 1 / 3 / 5 - SEM - REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />BED - 1 / 2 - SEM - REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />BED - 2 - SEM - REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />MED - 1 - SEM - REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />MED - 2 - SEM - REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />M.SC (CHEMISTRY) - 2 / 4 - SEM - REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />M.SC (CHEMISTRY) - 2 - SEM - REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />B.SC ( NEP) - 1 /3 / 5 - SEM - REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />B.SC ( NEP) - 2 / 4 - SEM - REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />B.COM (COM) NEP - 1 / 2 / 3 - SEM - REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />B.COM (COM) NEP - 2 / 4 - SEM - REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />B.COM (PLAIN) NEP - 1 / 2 / 3 - SEM - REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />B.COM (PLAIN) NEP - 2 / 4 - SEM - REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />M.PHARM (PRA) - 2 / 4 - SEM - REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />M.PHARM (PCT) - 2 / 4 - SEM - REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />M.PHARM (PCG) - 1 - SEM - REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />M.PHARM (PCG) - 2 / 4 - SEM - REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />M.PHARM (PCL) - 1 / 3 - SEM - REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />M.PHARM (PCL) - 2 / 4 - SEM - REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />BA (NEP) - 1 / 2 / 3 / 4 - SEM - REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />BA (NEP) - 2 - SEM - REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />BA (NEP) - 4 - SEM - REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>

            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />B.SC (AG) - 1/2 SEM REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />B.SC (AG) - 3 SEM REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />B.SC (AG) - 4 SEM REGULAR / REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />B.SC (AG) - 5 SEM REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />B.SC (AG) - 6 SEM REGULAR / REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />B.TECH (AG) - 2 / 5 SEM REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />B.TECH (AG) - 4 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />B.TECH (AG) - 6 SEM REGULAR / REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />B.TECH (AG) - 7 SEM REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />M.SC (AG) - 1 SEM REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />M.SC (AG) - 2 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />BCA (NEP) - 1 / 3 SEM REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />BCA (NEP) - 2 / 4 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />MCA  - 1 SEM REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />MCA  - 2 SEM REGULAR / REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />BALLB - 1 / 2 / 3 / 5 / 6 / 7 / 8 / 9 SEM REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />BALLB - 2 / 4 / 6 / 8 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />LLB - 1 / 2 / 3 SEM REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />LLB - 2 / 4 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>

            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />BA - 5 SEM REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />BA - 6 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />BA (NEP) - 5 SEM REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />BA (NEP) - 6 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>

            <p></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />BCA (NEP) - 5 SEM REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />BCA (NEP) - 6 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />B.PHARM - 7 SEM REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />M.SC (BIOTECH) - 1/3 SEM REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />M.SC (BIOTECH) - 2/4 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />M.SC (CS) - 2/4 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />M.SC (CS) - 3 SEM REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />M.SC (FST) - 2/4 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />M.SC (MATH) - 2/4 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />M.SC (MATH) - 4 SEM REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />M.SC (MICRO) - 2/4 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />M.SC (PHYSICS) - 2 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />M.SC (ZOOLOGY) - 2/4 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />M.SC (BOTANY) - 2 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />MSW - 2/4 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>

            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />M.TECH (CSE) - 2 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />M.TECH (EPS) - 1/2 SEM REAPPEAR /REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />M.TECH (PS/PIE) - 2 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />M.TECH (PIE) - 3 SEM REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />M.TECH (THERMAL) - 2 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />MA (ECONOMICS) - 4 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />MA (HINDI ) - 2/4 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />MA (ENGLISH) - 1/3 SEM REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />MA (ENGLISH) - 2/4 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />MA (HISTORY) - 3/4 SEM REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />MA (HISTORY) - 4 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />MA (PS) - 1 SEM REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />MA (PS) - 2/4 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />MA (SOCIO) - 2/4 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />BALLB - 9 SEM REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />BALLB - 10 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />LLB - 5 SEM REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />LLB - 6 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />LLM - 1 SEM REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />LLM - 2 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />B.PHARM - 8 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />B.PHARM (LATERAL) - 8 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>

            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />BE (CE/CSE/EE/ECE/ME) - 7 SEM REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />BE (CE/EEE/EE/IT/ME) LATERAL - 7 SEM REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />BE (EE/CE/CSE/EEE/ECE/ME) - 8 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />BE (CE/CSE/EEE/EE/ECE/IT/ME) LATERAL - 8 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />BED - 3 SEM REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />BED - 4 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />MED - 3 SEM REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />MED - 4 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>

            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />BE (CE/CSE/EE/ET/ME) - 7 SEM REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />BE (CE/EEE/EE/IT/ME) LATERAL - 7 SEM REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />BE (EE/CE/CSE/EEE/ECE/ME) - 8 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />BE (CE/CSE/EEE/EE/ECE/IT/ME) LATERAL - 8 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />BED - 3 SEM REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />BED - 4 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />MED - 3 SEM REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />MED - 4 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>

            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />B.SC ( NEP) - 6 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />DIPLOMA (CE/CSE/EE/ET/ME) - 6 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />DIPLOMA (ME) 2ND SHIFT - 6 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />DIPLOMA (CE/CSE/EE/ET/ME) LATERAL  - 6 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />DIPLOMA (CSE) LATERAL  - 5 & 6 SEM REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />B.COM (PLAIN/COM) - 5 SEM REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />B.COM  (PLAIN/COM) NEP - 5 SEM REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />B.COM (PLAIN/COM) - 6 SEM REGULAR/REAPPEAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />B.COM  (COM) NEP - 6 SEM REGULAR </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />M.COM - 1, 2, 4 SEM REAPPEAR  </strong> </a></p> 	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" /> B.SC (AG) -SEM 8 - REGULAR</strong></a></p>	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" /> MCA - SEM 4 - REGULAR</strong></a></p>	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" /> BAMS - SEM 1 - REGULAR</strong></a></p>	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />BBA (NEP)5 SEM REAPPEAR</strong> </a></p>	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p><p><a href="https://erplive.rkdf.ac.in/" target="_blank"><strong><img src="images/img/new4.gif" />BBA (NEP)6 SEM REGULAR</strong> </a></p>	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>
            <p>&nbsp;</p>
            <p><a href="https://rkdfu.org/new_diplomaAG_result.php" target="_blank"><strong><img src="images/img/new4.gif" />Diploma AG Results - June 2025</strong> </a></p>
            <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span
                    class="style8">&nbsp;( Last date of Revaluation Next 10 days)</span></p>

            <p style="font-size: medium;font-style: normal;font-weight: bolder;color: navy;">&nbsp;

        </section>
        <!--- contentLeft -->
        <section id="sideBar">
            <aside id="customMenu" class="sidebarWidget">
                <h2> Result </h2>
                <div class="glossymenu">
                    <!--<a class="menuitem" href="erp.rkdf.ac.in"><img src="images/bullet.png" /> Enrollment Form </a>-->

                    <a class="menuitem" href="exam.php"><img src="images/bullet.png" /> Examination </a>
                    <a class="menuitem" href="examtimetable.php"><img src="images/bullet.png" /> Exam Time
                        Table</a>
                    <a class="menuitem" href="Result.php"><img src="images/bullet.png" /> Result </a>
                    <a class="menuitem" href="result/revel_form.pdf" target="_blank"><img src="images/bullet.png" />
                        Revaluation Form</a>
                    <a class="menuitem" href="forms/Application For Hindi.pdf" target="_blank"><img
                            src="images/bullet.png" />Degree form Hindi </a>
                    <a class="menuitem" href="forms/Application For English.pdf" target="_blank"><img
                            src="images/bullet.png" />Degree form English </a>
                </div>
                <!--<a name="ex1" id="ex1"></a>
                    -->
            </aside>
        </section>
        <!--- sideBar -->
        <br class="clear" />
    </section>
    <!--- content -->
    <script type="text/javascript">
    jQuery(document).ready(function($) {
        $('#mainNav li').hover(
            function() {
                jQuery(this).find('.dropdown').fadeIn(300);
            },
            function() {
                jQuery(this).find('.dropdown').fadeOut(200);
            }
        );
    });
    </script>
    </div>
  </section>

  <!-- APPROVED FOOTER -->
  <?php include __DIR__ . '/include/footer.php'; ?>

</body>
</html>
